export const FETCH_BEERS_START = 'FETCH_BEERS_START';
export const FETCH_BEERS_FAIL = 'FETCH_BEERS_FAIL';
export const FETCH_BEERS_SUCCESS = 'FETCH_BEERS_SUCCESS';

export const TOGGLE_FAVORITE = 'TOGGLE_FAVORITE';
export const SET_FILTERS = 'SET_FILTERS';

export const SEND_REVIEW = 'SEND_REVIEW';

export const FETCH_REVIEWS_START = 'FETCH_REVIEWS_START';
export const FETCH_REVIEWS_SUCCESS = 'FETCH_REVIEWS_SUCCESS';
export const FETCH_REVIEWS_FAIL = 'FETCH_REVIEWS_FAIL';
export const FETCH_RATING_SUCCESS = 'FETCH_RATING_SUCCESS';
export const FETCH_ALL_RATING_SUCCESS = 'FETCH_ALL_RATING_SUCCESS';
export const FETCH_USER_RATING_SUCCESS = 'FETCH_USER_RATING_SUCCESS';
