export const FETCH_BEERS_START = 'FETCH_BEERS_START';
export const FETCH_BEERS_FAIL = 'FETCH_BEERS_FAIL';
export const FETCH_BEERS_SUCCESS = 'FETCH_BEERS_SUCCESS';
export const TOGGLE_FAVORITE = 'TOGGLE_FAVORITE';
export const SET_FILTERS = 'SET_FILTERS';
